# Generated by Django 2.1.5 on 2019-02-08 17:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0004_auto_20190208_0205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationdata',
            old_name='phon',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2019, 2, 8, 17, 49, 10, 634290, tzinfo=utc)),
        ),
    ]
